version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: peluchemania_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_secreta
      MYSQL_DATABASE: peluchemania_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: